### ISSUE TITLE
selDateRange initialized with null

### ISSUE THREAD

**Issue by cedricleroy** [kekeh/mydaterangepicker#19]
Following this example: https://github.com/kekeh/mydaterangepicker/tree/master/sampleapp/sample-date-range-picker-normal

If selectedDateRangeNormal is initialized with null, it seems to break the data binding. If initialized as shown  in the example, it works. If initialized to undefined, it works too. Is it the desired behavior?

**Comment by kekeh** [comment]
Initialized with **null** or **undefined** should work same way. Check this line: https://github.com/kekeh/mydaterangepicker/blob/master/src/my-date-range-picker/my-date-range-picker.component.ts#L274

How it breaks the data binding? I executed the sampleapp and I initialized the **selectedDateRangeNormal** to **null** and it worked ok.

**Comment by cedricleroy** [comment]
I checked this line and have been confused, as you said should work on the same way.

So doing some further tests:

This work:
```typescript
  selectedDateRangeNormal:IMyDateRange = undefined;

  onDateRangeChanged(event: IMyDateRangeModel){
     console.log(event);
  }

  clearDateRange(){
    this.selectedDateRangeNormal = null;
  }
```

This work:
```typescript
  selectedDateRangeNormal:IMyDateRange = null;

  onDateRangeChanged(event: IMyDateRangeModel){
     console.log(event);
     if(event.formatted !== '') {
       this.selectedDateRangeNormal = {beginDate: event.beginDate, endDate: event.endDate};
     }
  }

  clearDateRange(){
    this.selectedDateRangeNormal = null;
  }
```

This does not work:
```typescript
  selectedDateRangeNormal:IMyDateRange = null;

  onDateRangeChanged(event: IMyDateRangeModel){
     console.log(event);
  }

  clearDateRange(){
    this.selectedDateRangeNormal = null;
  }
```
Code is here: https://github.com/cedricleroy/daterangepickettest

**Comment by kekeh** [comment]
In order to date range picker component detect the change (clear date range) the value of this.selectedDateRangeNormal should be changed every time.

Your first example works but only one clearDateRange() call because undefined !== null. After you have called clearDateRange() its value is null and if you call again and set value again to null, component is not detecting change.

Second example clearDateRange() call works every time because you set new value to the this.selectedDateRangeNormal in the onDateRangeChanged() function. This is right way if you want to clear date range by clearDateRange() function.

Third example doesn't work because there is not change at all.

This function is listening changes: https://github.com/kekeh/mydaterangepicker/blob/master/src/my-date-range-picker/my-date-range-picker.component.ts#L257

**Comment by cedricleroy** [comment]
Yea, I think it makes sense. Thanks for the explanations!
