### ISSUE TITLE
Icons out of the box do not work

### ISSUE THREAD

**Issue by xtreemrage** [kekeh/mydaterangepicker#4]
I have followed your example app and I see the daterangepicker and it works, but out-of-the-box I don't see the icons.  e.g. icon-calendar, cross, left/right.

How can I fix this?

[Example](http://imgur.com/a/ehvPM)

**Comment by kekeh** [comment]
Icon definition are here: https://github.com/kekeh/mydaterangepicker/blob/master/src/my-date-range-picker/my-date-range-picker.component.css

starting from  **@font-face** line

When you build you application it is possible that result is invalid because one backslash character is missing from **content** CSS property. If compiled result is string there must be two backslash before every **e** letter like below.

.mydrp .icon-calendar:before{content:\"\\e600\"}
.mydrp .icon-cross:before{content:\"\\e602\"}
.mydrp .icon-left:before{content:\"\\e605\"}
.mydrp .icon-right:before{content:\"\\e607\"}

Check build result first and try to manually add extra backlash if it is missing.

I did gulp task. It adds extra backslash before **e** letter: https://github.com/kekeh/mydaterangepicker/blob/master/gulpfile.js

Line 59 above file.

CSS file accepts only one backslash but if you compile CSS to string it need two backslash. I don't know better solution.

**Comment by kekeh** [comment]
I did fix so that npm package of the component contain template and styles as inline string parameters.

The styles string contain already double backslash when needed. Package do not contain any more separate CSS and HTML files.

Try the latest version 0.0.18

**Comment by xtreemrage** [comment]
Thanks will try it out
