### ISSUE TITLE
Limit the number of day that the user can pick

### ISSUE THREAD

**Issue by jtaoufik** [kekeh/mydaterangepicker#63]
Hi,
I'd like to limit the number the day to a variable score I have where every 5 points will give you 1 day to pick in the interval, any idea how to achieve that ?

**Comment by kekeh** [comment]
Hi @jtaoufik 

I don't understand your point. But you can disable dates and enable disabled dates with options.

**Comment by jtaoufik** [comment]
My point is that I want to limit the range depending of a predefined variable like 5 days can be selected if you have 5 credits

**Comment by kekeh** [comment]
You can limit the range using disable options. But not predefined variable. 

You can use **disableUntil** option which disable past dates and **disableSince** option which disables future dates.

For example set disableUntil (disable until today):
```javascript
let d: Date = new Date();
disableUntil: {year: g.getFullYear(), month: d.getMonth() + 1, day: d.getDate()};
```
Then you have to calculate **disableSince** value based on your predefined variable. You can change value of both options dynamically.

For example (disable since today + 5 days):
```javascript
let credits: number = 5;
let d: Date = new Date();
d.setDate(d.getDate() + credits);
disableSince: {year: g.getFullYear(), month: d.getMonth() + 1, day: d.getDate()};
```
This https://github.com/kekeh/mydaterangepicker/issues/61 issue contain example on how to change option dynamically. You have create copy of options and then change value of option.

Does this answer to your question?

**Comment by jtaoufik** [comment]
Not really since I want to add a listener when he clicks the start date and then calculate using the credits the max date he can chooses.

**Comment by jtaoufik** [comment]
There's no listener on the first date picked ?

**Comment by kekeh** [comment]
There is caalback. Check this: https://github.com/kekeh/mydaterangepicker#dateselected-callback
