### ISSUE TITLE
Setting selDateRange outputs 0-00-00 - 0-00-00

### ISSUE THREAD

**Issue by moritzgloeckl** [kekeh/mydaterangepicker#90]
Hi there,

I'm using the date range picker like this:

```
<my-date-range-picker name="mydaterange" [(ngModel)]="dateRange" [options]="myDateRangePickerOptions" [selDateRange]="'2017-11-14 - 2017-11-20'"></my-date-range-picker>

myDateRangePickerOptions: IMyDrpOptions = {
	dateFormat: 'yyyy-mm-dd',
	showClearBtn: false,
	showApplyBtn: false,
	showSelectDateText: false,
	disableUntil: this.todayStruct
};
```

But it just shows `0-00-00 - 0-00-00` in the input field. I've stepped through the code with the debugger and the splitting works but somewhere it messes my date range up. 

Seems like either I'm doing something terribly wrong or there's a bug!

**Comment by kekeh** [comment]
You can set initial range many ways.
```html
[selDateRange]="dateRange"
```

```javascript
dateRange:string = '2017-11-14 - 2017-11-20';
// or
dateRange:IMyDateRange = {
    beginDate: {year: 2017, month: 11, day: 14}, 
    endDate: {year: 2017, month: 11, day: 20}
};
```
or remove the **selDateRange** attribute and use **ngModel** like here: https://github.com/kekeh/mydaterangepicker#1-ngmodel-binding

because you are using the **ngModel** then the better solution to set initial date is done it like link above. There has been some problems when using the **ngModel** and the **selDateRange** attributes at the same time.

**Comment by moritzgloeckl** [comment]
Oh well thank you!
